PLAT-524 docker login fix
openhie/package-starter-kit pull request #25
Opened 2022-10-20 09:25 UTC by Mark-Labuschagne

2022-10-24 06:06 UTC, CastelloDev approved these changes

2022-10-27 09:47 UTC, nour-borgi requested changes
I m having issues 
![image](https://user-images.githubusercontent.com/48720958/198252094-ba5fe6cd-4a6a-4c58-bced-944ef5a94f20.png)

I did as you mentioned in the description.

**It is not an issue**, just check the openhie version in Dockerfile, should be latest (if you used yarn docker:build command).

2022-10-27 10:13 UTC, nour-borgi reviewed
No able to test it as I don't have docker access.

2022-10-27 17:05 UTC, marrouchi commented
Can't we add a `docker login` CMD in the DockerFile and pass on the credentials as env vars ?

2023-01-16 12:38 UTC, merged