CLI-V2 pre prod #3
openhie/package-starter-kit pull request #33
Opened 2022-12-12 13:00 UTC by Mark-Labuschagne

Don't review yet, these PRs are first being structured in the most convenient fashion.

### What this PR does
- unmarshal config from config file
- get config options from command line parameters
- instantiates config into a stored variable for use in coming config related functions

### Testing
- refer to unit tests

2023-01-02 12:31 UTC, nour-borgi commented on cli/src/core/state/config.go
> +		configViper.SetConfigType("yaml")
isn't the type yml ?

2023-01-02 14:56 UTC, marrouchi approved these changes

2023-01-03 07:25 UTC, Mark-Labuschagne commented on cli/src/core/state/config.go
> +		configViper.SetConfigType("yaml")
Same thing

2023-01-03 07:51 UTC, marrouchi requested changes

2023-01-03 07:51 UTC, marrouchi commented on cli/src/core/parse/config.go
> +	}
```suggestion
	if err != nil {
	    if strings.Contains(err.Error(), "expected type") {
		return nil, errors.Wrap(ErrInvalidConfigFileSyntax, "")
	    } else {
	        return nil, errors.Wrap(err, "")
	    }
	}
```

2023-01-04 07:06 UTC, marrouchi approved these changes

2023-01-10 10:05 UTC, nour-borgi approved these changes

2023-01-10 10:55 UTC, merged